### ISSUE TITLE
UNHANDLED_ERROR - status 404

### ISSUE THREAD

**Issue by leon3291** [mohankumarpaluru/oracle-freetier-instance-creation#18] opened 2024-05-27 22:33 UTC
The script encountered an unhandled error and exited unexpectedly.

Please re-run the script by executing './setup_init.sh rerun'.

And raise a issue on GitHub if its not already existing:
https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/issues

 And include the following error message to help us investigate and resolve the problem:

status: 404
code: NotAuthorizedOrNotFound
message: Authorization failed or requested resource not found.

Please help me, i really need that machine. Thx in advance.

**Comment by mohankumarpaluru** [comment] 2024-05-28 03:09
Duplicate of #17 

please try by pulling the code from the branch `LimitExceeded-false-positive-fix` and let me know if you are still facing the issue

**Comment by mohankumarpaluru** [comment] 2024-06-05 13:57
Resolved by PR #20

**Closed by mohankumarpaluru** 2024-06-05 13:57 UTC
